prefix_dir : ../../saves
plots_dir  : ../../plots
plots      : True 
table      : True

name_folder:
  FedAvg : fed_avg
  SplitFed-MS : sl_multi_server
  SplitFed-SS : sl_single_server
  CSE-FSL : cse_fsl
  FSL-SAGE : fsl_sage

experiments:
  cifar10/simpleconv_linaux/iid:
    disable : false
    title : CIFAR10; iid; SimpleConv; LinearAux 
    desc  : Simple convolutional classifier model with a linear auxiliary network
    test_ids: [0, 1, 2, 3, 4]
    model : simple_conv
    dataset : cifar10
    distribution : iid
    save_locs:
      FedAvg    : R200m3E1B128-seed200/241215-111308
      SplitFed-MS  : R200m3E1B128-seed200/241215-111308
      SplitFed-SS  : R200m3E1B128-seed200/241215-111308
      CSE-FSL   : R200m3E1B128q5-seed200/241221-220456
      FSL-SAGE  : R200m3E1B128q5l10-seed200/241222-142715

  cifar10/simpleconv_linaux/noniid:
    disable : false
    title : CIFAR10; noniid; SimpleConv; LinearAux 
    desc  : Simple convolutional classifier model with a linear auxiliary network, on non-iid partitioned CIFAR10
    test_ids: [0, 1, 2, 3, 4]
    model : simple_conv
    dataset : cifar10
    distribution : noniid
    save_locs:
      FedAvg    : R200m3E1B128-seed200/241215-181350
      SplitFed-MS  : R200m3E1B128-seed200/241215-181350
      SplitFed-SS  : R200m3E1B128-seed200/241215-181350
      CSE-FSL   : R200m3E1B128q5-seed200/241215-181350
      FSL-SAGE  : R200m3E1B128q5l10-seed200/241215-181350

  cifar10/simpleconv_2layeraux:
    disable : true
    full_dirs : true
    title : SimpleConv; 2LayerAux
    desc  : Effect of auxiliary model size with 1 and 2 layer auxiliary networks
    test_ids : [0, 1, 2, 3]
    save_locs:
      CSE-FSL (Aux1)  : cse_fsl/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012005
      FSL-SAGE (Aux1) : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012109
      CSE-FSL (Aux2)  : cse_fsl/simple_conv/cifar-iid/U3E1BR5L10-200/241206-013049
      FSL-SAGE (Aux2) : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-021238
    result_files:
      CSE-FSL (Aux1)  : results
      FSL-SAGE (Aux1) : results
      CSE-FSL (Aux2)  : results
      FSL-SAGE (Aux2) : results

  cifar10/resnet18/iid:
    disable : false
    title : CIFAR10; iid, Resnet18; Cut@L3
    desc  : Resnet18 cut at Layer 3 and run for 500 rounds
    test_ids : [0, 1, 2, 3, 4]
    model : resnet18
    dataset: cifar10
    distribution: iid
    save_locs:
      FedAvg    : R200m3E1B128-seed200/241215-111941
      SplitFed-MS  : R200m3E1B128-seed200/241215-113251
      SplitFed-SS  : R200m3E1B128-seed200/241215-112611
      CSE-FSL   : R200m3E1B128q5-seed200/241215-115901
      FSL-SAGE  : R200m3E1B128q5l10-seed200/241215-115904

  cifar10/resnet18/noniid:
    disable : false
    title : CIFAR10; noniid, Resnet18; Cut@L3
    desc  : Resnet18 cut at Layer 3 and run for 500 rounds for non-iid client data
    test_ids : [0, 1, 2, 3, 4]
    model : resnet18
    dataset : cifar10
    distribution: noniid
    save_locs:
      FedAvg    : R200m3E1B128-seed200/241215-181350
      SplitFed-MS  : R200m3E1B128-seed200/241215-181350
      SplitFed-SS  : R200m3E1B128-seed200/241215-181350
      CSE-FSL   : R200m3E1B128q5-seed200/241215-185921
      FSL-SAGE  : R200m3E1B128q5l10-seed200/241215-190000

  cifar10/simpleconv_alignment_ablation:
    disable : true
    full_dirs: true
    title : Effect of Alignment Interval
    desc  : Effect of alignment interval tested for 2, 5, 10, and 20 rounds, with linear aux model and on CIFAR-10
    test_ids : [0, 1, 2, 3]
    save_locs: 
      $l=2$   : fsl_sage/simple_conv/cifar-iid/U3E1BR5L2-200/241206-015359
      $l=5$   : fsl_sage/simple_conv/cifar-iid/U3E1BR5L5-200/241206-015431
      $l=10$  : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012109
      $l=20$  : fsl_sage/simple_conv/cifar-iid/U3E1BR5L20-200/241206-015629
    result_files:
      $l=2$   :  results 
      $l=5$   :  results
      $l=10$  :  results
      $l=20$  :  results

  cifar10_dbg/simpleconv:
    disable : false
    full_dirs: true
    title : none
    desc : none
    test_ids : [0,1]
    save_locs:
      CSE : saves_dbg/cse_fsl/simple_conv/cifar-iid/U3E1BR5L10-200/241222-013655
      SAGE : saves_dbg/fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241222-013555
