client:
  align: 10
  batch_size: 128
  dataset: cifar
  device: &id001 !!python/object/apply:torch.device
  - cuda
  epoch: 1
  gradSteps: 100
  lr: 0.001
  lr_decay: false
server:
  activated: 3
  align: 10
  batch_size: 128
  client: 3
  dataset: cifar
  device: *id001
  lr: 0.001
  round: 200
  t_round: 4
u_args:
  batch_round: 5
  batch_size: 128
  client: 3
  dataset: cifar
  device: *id001
  dt: false
  method: sl_single_server
  sample: iid
  save: true
  seed: 200
