defaults:
  - dataset   : cifar10
  - model     : simple_conv
  - algorithm : fsl_sage
  - optional dataset_model : ${dataset}_${model}
  - optional dataset_model_algorithm : ${dataset}_${model}_${algorithm}

  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  - override hydra/launcher: joblib

save   : True
save_dir_prefix : ../saves
seed   : 200
device : cuda
use_64bit: false
num_workers : 0

rounds      : 200
num_clients : 10
agg_factor  : auto
checkpoint_interval : 5

comm_threshold_mb : 204800  # corresponds to 200 GiB

# to prevent logging and working directory creation by hydra
hydra:  
  output_subdir: null  
  run:  
    dir: .
  launcher:
    n_jobs: 8
    backend: loky 
    prefer: processes
    verbose: 1
