prefix_dir : ../saves
plots_dir  : ../plots
plots      : True 
table      : True

experiments:
  cifar10_simpleconv_linaux:
    title : SimpleConv; LinearAux 
    desc  : Simple convolutional classifier model with a linear auxiliary network
    test_ids: [0, 1, 2, 3, 4]
    save_locs:
      FedAvg    : fed_avg/simple_conv/cifar-iid/U3E1BR5L10-200/241206-011931
      Split-MS  : sl_multi_server/simple_conv/cifar-iid/U3E1BR5L10-200/241206-011934
      Split-SS  : sl_single_server/simple_conv/cifar-iid/U3E1BR5L10-200/241206-011931
      CSE-FSL   : cse_fsl/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012005
      FSL-SAGE  : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012109
    result_files:
      FedAvg    : test_metrics
      Split-MS  : test_metrics
      Split-SS  : test_metrics
      CSE-FSL   : results
      FSL-SAGE  : results

  cifar10_simpleconv_2layeraux:
    title : SimpleConv; 2LayerAux
    desc  : Effect of auxiliary model size with 1 and 2 layer auxiliary networks
    test_ids : [0, 1, 2, 3]
    save_locs:
      CSE-FSL (Aux1)  : cse_fsl/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012005
      FSL-SAGE (Aux1) : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012109
      CSE-FSL (Aux2)  : cse_fsl/simple_conv/cifar-iid/U3E1BR5L10-200/241206-013049
      FSL-SAGE (Aux2) : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-021238
    result_files:
      CSE-FSL (Aux1)  : results
      FSL-SAGE (Aux1) : results
      CSE-FSL (Aux2)  : results
      FSL-SAGE (Aux2) : results

  cifar10_resnet18_cutl3_500runs:
    title : Resnet18; Cut@L3
    desc  : Resnet18 cut at Layer 3 and run for 500 rounds
    test_ids : [0, 1, 2, 3, 4]
    save_locs:
      FedAvg    : fed_avg/resnet18/cifar-iid/U3E1BR5L10-200/241206-014034
      Split-MS  : sl_multi_server/resnet18/cifar-iid/U3E1BR5L10-200/241206-014309
      Split-SS  : sl_single_server/resnet18/cifar-iid/U3E1BR5L10-200/241206-014212
      CSE-FSL   : cse_fsl/resnet18/cifar-iid/U3E1BR5L10-200/241206-014409
      FSL-SAGE  : fsl_sage/resnet18/cifar-iid/U3E1BR5L10-200/241206-014449
    result_files:
      FedAvg    : test_metrics
      Split-MS  : test_metrics
      Split-SS  : test_metrics
      CSE-FSL   : results
      FSL-SAGE  : results

  simpleconv_alignment_ablation:
    title : Effect of Alignment Interval
    desc  : Effect of alignment interval tested for 2, 5, 10, and 20 rounds, with linear aux model and on CIFAR-10
    test_ids : [0, 1, 2, 3]
    save_locs: 
      $l=2$   : fsl_sage/simple_conv/cifar-iid/U3E1BR5L2-200/241206-015359
      $l=5$   : fsl_sage/simple_conv/cifar-iid/U3E1BR5L5-200/241206-015431
      $l=10$  : fsl_sage/simple_conv/cifar-iid/U3E1BR5L10-200/241206-012109
      $l=20$  : fsl_sage/simple_conv/cifar-iid/U3E1BR5L20-200/241206-015629
    result_files:
      $l=2$   :  results 
      $l=5$   :  results
      $l=10$  :  results
      $l=20$  :  results