prefix_dir : ../saves
plots_dir  : ../../plots
plots      : True 
table      : True

name_folder:
  FedAvg : fed_avg
  SplitFed-MS : sl_multi_server
  SplitFed-SS : sl_single_server
  CSE-FSL : cse_fsl
  FSL-SAGE : fsl_sage

experiments:
  cifar10/resnet18_aux:
    disable : false
    full_dirs : true
    title : ResNet18; Abalate Model Sizes
    desc  : Abalation of model sizes for the resnet-18 models
    test_ids : [0, 1, 2, 3, 4, 5, 6, 7]
    accuracy_mark_level: 0.81
    loss_mark_level: 0.65
    distribution: iid
    save_locs:
      FSL-SAGE (Linear)  : fsl_sage/resnet18/cifar10-iid/R9999999m10E1B256q5l10-seed200/769fad7a496dfabb684a16ddb0cff0bd55291fd317a41a53a5d158d99add0e79
      FSL-SAGE (Half) : fsl_sage/resnet18/cifar10-iid/R9999999m10E1B256q5l10-seed200/250521-201811
      FSL-SAGE (Normal)  : fsl_sage/resnet18/cifar10-iid/R9999999m10E1B256q5l10-seed200/f7c0264e1d104ec88958c19889a7829c2588c5645170149e5f3f1ca9fbd64985
      FSL-SAGE (Full) : fsl_sage/resnet18/cifar10-iid/R9999999m10E1B256q5l10-seed200/250521-201809
      CSE-FSL (Linear)  : cse_fsl/resnet18/cifar10-iid/R9999999m10E1B256q5-seed200/250522-005904
      CSE-FSL (Half)  : cse_fsl/resnet18/cifar10-iid/R9999999m10E1B256q5-seed200/b0c774155c9b8d81f1cb7f13bf0ceffb7cf9eef8e09017ab44c46797433bb6ea
      CSE-FSL (Normal)  : cse_fsl/resnet18/cifar10-iid/R9999999m10E1B256q5-seed200/e3a86bd626d5eb55e987a1224f53d9519052a9941eadaa9cb0aa03f9520a5c81
      CSE-FSL (Full)  : cse_fsl/resnet18/cifar10-iid/R9999999m10E1B256q5-seed200/c9b07a6541b93cb706b0b3502440c8fa7dd081dec4a9b7b514e5e7c78b191367
    result_files:
      FSL-SAGE (Linear)  : results
      FSL-SAGE (Half) : results
      FSL-SAGE (Normal)  : results
      FSL-SAGE (Full) : results
      CSE-FSL (Linear)  : results
      CSE-FSL (Half)  : results
      CSE-FSL (Normal)  : results
      CSE-FSL (Full)  : results

  